In [1]:
import numpy as mp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('path_prediction_dataset.csv')
df

,icao24,callsign,origin_country,time_position,longitude,latitude,baro_altitude,velocity,heading,vertical_rate,on_ground,origin_airport,destination_airport,aircraft_type,position_source,distance_to_nearest_aircraft,airspace_class,alert_level
0,s9t0u1,QTR321,UK,2025-07-30 10:00:00,-119.859959,71.429228,14958.846358,429.815012,79.315873,-31.816979,False,CDG,HND,B777,ADS-B,1.810134,A,NaN
1,j0k1l2,AAL789,Canada,2025-07-30 10:00:10,177.419097,-80.521963,37446.471265,487.548982,291.652021,-33.884497,False,ORD,LAX,B737,ADS-B,4.845806,G,NaN
2,m3n4o5,DAL456,USA,2025-07-30 10:00:20,22.684660,-64.493309,23222.374222,206.554212,299.188774,-11.563410,False,KSFO,LHR,Gulfstream,ADS-B,41.922594,C,NaN
3,s9t0u1,AFR987,UK,2025-07-30 10:00:30,-51.616152,17.684783,11546.412210,236.537147,19.585006,-13.821284,True,IAH,YYZ,B777,Radar,24.685921,A,NaN
4,g7h8i9,UAL123,UK,2025-07-30 10:00:40,-76.247030,21.443679,39277.957489,200.790543,256.299881,36.695787,False,ORD,YYZ,A350,Multilateration,46.968817,C,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,m3n4o5,AAL789,India,2025-07-30 23:52:30,143.961499,-65.567244,16965.204167,573.990790,70.298917,-2.173605,False,ORD,DFW,A320,ADS-B,2.073952,A,NaN
4996,p6q7r8,BAW654,France,2025-07-30 23:52:40,-54.692612,-55.659317,3642.082997,385.598479,181.713350,35.810729,False,DXB,BOM,A350,Multilateration,21.539355,A,NaN
4997,g7h8i9,DAL456,UAE,2025-07-30 23:52:50,-139.847997,-45.907674,24883.866821,338.860185,105.806669,-33.826253,False,CDG,DFW,A320,Radar,41.417954,E,NaN
4998,g7h8i9,AAL789,USA,2025-07-30 23:53:00,73.495710,41.521927,39503.536113,529.568697,19.252681,25.707966,False,ORD,ATL,Embraer190,Multilateration,20.485783,D,NaN
4999,a1b2c3,DAL456,India,2025-07-30 23:53:10,82.210069,-73.991656,2740.851258,568.370215,181.335245,43.255258,False,JFK,BOM,A320,Radar,44.243892,D,NaN

In [4]:
import pandas as pd

# STEP 1: Load the CSV file
df = pd.read_csv("path_prediction_dataset.csv")

# STEP 2: Dataset overview
print("📄 DATASET STRUCTURE")
print("-" * 50)
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")
print("Column Names:", list(df.columns))

# STEP 3: Info about data types and missing values
print("\n🔍 COLUMN DATA TYPES & MISSING VALUES")
print("-" * 50)
print(df.info())

# STEP 4: Descriptive statistics for numeric columns
print("\n📊 NUMERICAL STATISTICS")
print("-" * 50)
print(df.describe())

# STEP 5: Frequency count of key categorical columns
categorical_cols = ['aircraft_type', 'position_source', 'airspace_class', 'alert_level', 'on_ground']
print("\n📈 FREQUENCY COUNTS FOR CATEGORICAL COLUMNS")
print("-" * 50)
for col in categorical_cols:
    if col in df.columns:
        print(f"\n{col.upper()} value counts:")
        print(df[col].value_counts(dropna=False))

# STEP 6: Correlation matrix
print("\n🔗 CORRELATION MATRIX")
print("-" * 50)
print(df.corr(numeric_only=True))

📄 DATASET STRUCTURE
--------------------------------------------------
Rows: 5000
Columns: 18
Column Names: ['icao24', 'callsign', 'origin_country', 'time_position', 'longitude', 'latitude', 'baro_altitude', 'velocity', 'heading', 'vertical_rate', 'on_ground', 'origin_airport', 'destination_airport', 'aircraft_type', 'position_source', 'distance_to_nearest_aircraft', 'airspace_class', 'alert_level']

🔍 COLUMN DATA TYPES & MISSING VALUES
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   icao24                        5000 non-null   object
 1   callsign                      5000 non-null   object
 2   origin_country                5000 non-null   object
 3   time_position                 5000 non-null   object
 4   longitude                     5000 non-null   float64
 5   latitude                      5000 non-null   float64
 6   baro_altitude                 5000 non-null   float64
 7   velocity                      5000 non-null   float64
 8   heading                       5000 non-null   float64
 9   vertical_rate                 5000 non-null   float64
 10  on_ground                     5000 non-null   bool
 11  origin_airport                5000 non-null   object
 12  destination_airport           5000 non-null   object
 13  aircraft_type                 5000 non-null   object
 14  position_source               5000 non-null   object
 15  distance_to_nearest_aircraft  5000 non-null   float64
 16  airspace_class                5000 non-null   object
 17  alert_level                   700 non-null    object
dtypes: bool(1), float64(7), object(10)
memory usage: 669.1+ KB
None

📊 NUMERICAL STATISTICS
--------------------------------------------------
         longitude     latitude  baro_altitude     velocity      heading  \
count  5000.000000  5000.000000    5000.000000  5000.000000  5000.000000
mean      0.001271    -0.705672   20964.254120   353.481387   179.613239
std     103.157972    51.706724   11600.506224   144.663826   103.541962
min    -179.957288   -89.968407     900.372769   100.010259     0.036854
25%     -87.551104   -45.683925   10928.442561   229.424292    91.783268
50%       0.670579    -1.088322   20809.690399   355.932718   180.625010
75%      87.635421    42.921533   31094.924612   478.484393   268.614279
max     179.881072    89.980680   40980.677070   599.945531   359.990592

       vertical_rate  distance_to_nearest_aircraft
count    5000.000000                   5000.000000
mean       -0.528388                     25.240586
std        28.728559                     14.399390
min       -49.960914                      0.100421
25%       -25.301361                     13.015533
50%        -0.676234                     25.301927
75%        24.302984                     37.782243
max        49.989968                     49.996991

📈 FREQUENCY COUNTS FOR CATEGORICAL COLUMNS
--------------------------------------------------

AIRCRAFT_TYPE value counts:
aircraft_type
B777          747
A350          741
Embraer190    737
A320          707
B737          702
Cessna172     694
Gulfstream    672
Name: count, dtype: int64

POSITION_SOURCE value counts:
position_source
Radar              1691
ADS-B              1689
Multilateration    1620
Name: count, dtype: int64

AIRSPACE_CLASS value counts:
airspace_class
B    876
G    870
E    844
D    809
C    804
A    797
Name: count, dtype: int64

ALERT_LEVEL value counts:
alert_level
NaN         4300
Advisory     486
Warning      161
Critical      53
Name: count, dtype: int64

ON_GROUND value counts:
on_ground
False    4520
True      480
Name: count, dtype: int64

🔗 CORRELATION MATRIX
--------------------------------------------------
                              longitude  latitude  baro_altitude  velocity  \
longitude                      1.000000 -0.005976       0.010464  0.009621
latitude                      -0.005976  1.000000       0.012977 -0.005035
baro_altitude                  0.010464  0.012977       1.000000 -0.005292
velocity                       0.009621 -0.005035      -0.005292  1.000000
heading                        0.027746 -0.022977       0.007239  0.003869
vertical_rate                  0.010916 -0.016499      -0.013147  0.020419
on_ground                      0.000865 -0.013971      -0.005251 -0.007269
distance_to_nearest_aircraft   0.014102  0.000104      -0.009502  0.002920

                               heading  vertical_rate  on_ground  \
longitude                     0.027746       0.010916   0.000865
latitude                     -0.022977      -0.016499  -0.013971
baro_altitude                 0.007239      -0.013147  -0.005251
velocity                      0.003869       0.020419  -0.007269
heading                       1.000000      -0.020923   0.000205
vertical_rate                -0.020923       1.000000   0.033666
on_ground                     0.000205       0.033666   1.000000
distance_to_nearest_aircraft  0.021126       0.013323  -0.021137

                              distance_to_nearest_aircraft
longitude                                         0.014102
latitude                                          0.000104
baro_altitude                                    -0.009502
velocity                                          0.002920
heading                                           0.021126
vertical_rate                                     0.013323
on_ground                                        -0.021137
distance_to_nearest_aircraft                      1.000000